version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-world-typescript"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vmzkvw35vkzc"
s3_prefix = "hello-world-typescript"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
[default.build.parameters]
beta_features = true
[default.sync.parameters]
beta_features = true
